DatabaseHelper.addProduct(getDatabase(), "applegala", new Product("Maçã Gala (Kg)", "Hortifruti", new Number(5.29f), null, new Pair<Number, Number>(2, 8)));
DatabaseHelper.addProduct(getDatabase(), "bananananica", new Product("Banana Nanica (Kg)", "Hortifruti", new Number(3.65f), null, new Pair<Number, Number>(1, 5)));
DatabaseHelper.addProduct(getDatabase(), "bananaterra", new Product("Banana da Terra (Kg)", "Hortifruti", new Number(12.09f), null, new Pair<Number, Number>(8, 16)));
DatabaseHelper.addProduct(getDatabase(), "bananaprata", new Product("Banana Prata (Kg)", "Hortifruti", new Number(5.16f), null, new Pair<Number, Number>(2, 8)));
DatabaseHelper.addProduct(getDatabase(), "grapeoutseed", new Product("Uva sem sementes", "Hortifruti", new Number(5.39f), null, new Pair<Number, Number>(2, 8)));
DatabaseHelper.addProduct(getDatabase(), "purplegarlic", new Product("Alho Roxo", "Hortifruti", new Number(6.59f), null, new Pair<Number, Number>(3, 9)));
DatabaseHelper.addProduct(getDatabase(), "onion", new Product("Cebola (Kg)", "Hortifruti", new Number(3.49f), null, new Pair<Number, Number>(0.50f, 6)));
DatabaseHelper.addProduct(getDatabase(), "lettuce", new Product("Alface Americana", "Hortifruti", new Number(4.19f), null, new Pair<Number, Number>(1, 7)));
DatabaseHelper.addProduct(getDatabase(), "cabbage", new Product("Repolho Verde (Un)", "Hortifruti", new Number(6.58f), null, new Pair<Number, Number>(3, 9)));
DatabaseHelper.addProduct(getDatabase(), "parsley", new Product("Salsa Picada", "Hortifruti", new Number(4.15f), null, new Pair<Number, Number>(1, 7)));
DatabaseHelper.addProduct(getDatabase(), "breadtrad", new Product("Pão de Forma Tradicional", "Pães", new Number(5.55f), null, new Pair<Number, Number>(2, 10)));
DatabaseHelper.addProduct(getDatabase(), "breadint", new Product("Pão de Forma Integral", "Pães", new Number(7.89f), null, new Pair<Number, Number>(3, 14)));
DatabaseHelper.addProduct(getDatabase(), "breadhotdog", new Product("Pão p/ Hot Dog", "Pães", new Number(4.79f), null, new Pair<Number, Number>(1, 8)));
DatabaseHelper.addProduct(getDatabase(), "cheesebread", new Product("Pão de Queijo (Kg)", "Pães", new Number(24.50f), null, new Pair<Number, Number>(15, 30)));
DatabaseHelper.addProduct(getDatabase(), "meatdesf", new Product("Carne Desfiada (Kg)", "Carnes", new Number(21.39f), null, new Pair<Number, Number>(15, 30)));
DatabaseHelper.addProduct(getDatabase(), "meatmoid", new Product("Carne Moida (Kg)", "Carnes", new Number(6.69f), null, new Pair<Number, Number>(3, 15)));
DatabaseHelper.addProduct(getDatabase(), "pork", new Product("Pernil Suino (Kg)", "Carnes", new Number(49.25f), null, new Pair<Number, Number>(35, 55)));
DatabaseHelper.addProduct(getDatabase(), "filetsteak", new Product("Picanha Bovina (Kg)", "Carnes", new Number(65.99f), null, new Pair<Number, Number>(50, 80)));
DatabaseHelper.addProduct(getDatabase(), "filetmignon", new Product("Filé Mignon (Kg)", "Carnes", new Number(78.28f), null, new Pair<Number, Number>(50, 90)));
DatabaseHelper.addProduct(getDatabase(), "guavapaste", new Product("Goiabada", "Doces", new Number(8.99f), null, new Pair<Number, Number>(5, 13)));
DatabaseHelper.addProduct(getDatabase(), "doceleite", new Product("Doce de leite", "Doces", new Number(13.25f), null, new Pair<Number, Number>(8, 18)));
DatabaseHelper.addProduct(getDatabase(), "leitecond", new Product("Leite condensado", "Doces", new Number(4.69f), null, new Pair<Number, Number>(1, 8));
DatabaseHelper.addProduct(getDatabase(), "pacoca", new Product("Paçoca (Un)", "Doces", new Number(0.50f), null, new Pair<Number, Number>(0.25, 2));
DatabaseHelper.addProduct(getDatabase(), "pemoleque", new Product("Pé-de-moleque (300g)", "Doces", new Number(8.17f), null, new Pair<Number, Number>(5, 11));

DatabaseHelper.addCategory(getDatabase(), "breads", new Category("Pães", "Padaria", false));
DatabaseHelper.addCategory(getDatabase(), "candies", new Category("Doces", "Alimentos", false));
DatabaseHelper.addCategory(getDatabase(), "alcoohol", new Category("Alcoólicas", "Bebidas", false));
DatabaseHelper.addCategory(getDatabase(), "soda", new Category("Refrigerantes", "Bebidas", false));
DatabaseHelper.addCategory(getDatabase(), "juices", new Category("Sucos", "Bebidas", false));
DatabaseHelper.addCategory(getDatabase(), "analgesics", new Category("Analgésicos", "Farmácia", false));
DatabaseHelper.addCategory(getDatabase(), "supplements", new Category("Suplementos", "Farmácia", false));
DatabaseHelper.addCategory(getDatabase(), "soap", new Category("Sabão", "Limpeza", false));
DatabaseHelper.addCategory(getDatabase(), "insecticide", new Category("Inseticidas", "Limpeza", false));
